model:
  type: "apm_backbone"
  sidechain_model_type: null
  model_config_path: BondFlow/config/model.yaml
inference: 
  num_designs: 32
  num_cycle: 1200
  output_prefix: BondFlow/experiment/cyclize/MC4R/condition_MC4R/
  write_trajectory: False
  inference_step: 200
  seed: null
design_config:
  use_partial_diffusion: false # set as true to use partial diffusion，set as false use full diffusion
  input_pdb: BondFlow/experiment/cyclize/MC4R/7PIU_target_fixed.cif
  contigs: [['New_10-20'],[A/40-A/56:seq_FIX:str_FIX,A/89-A/141:seq_FIX:str_FIX,A/171-A/210:seq_FIX:str_FIX,A/213-A/213:seq_FIX:str_FIX,A/251-A/297:seq_FIX:str_FIX]]
  length: null
  partial_t: null
  bond_condition: ["A/start-A/start|A/end-A/end:0:FIX","B|B","A|B","B|A"]
  hotspots: ["A/268","A/129","A/188","A/126","A/261"] #"A/126","A/261" are general, "A/268","A/129","A/188" are specificity
  write_full_chains: ['A']  # 如果为true，即使contig中只用了部分片段，最终也会把用到的片段所属的整个chain都写入PDB文件
interpolant:
  save_gt: false
  min_t: 0.01
  separate_t: false
  provide_kappa: false
  hierarchical_t: false
  codesign_separate_t: true
  codesign_forward_fold_prop: 0.25
  codesign_inverse_fold_prop: 0.25
  codesign_prop: -1.0
  cache_dir: "./cache"
  rots:
    corrupt: true
    train_schedule: linear
    sample_schedule: exp
    exp_rate: 10
    eps: 0.0001
    batch_ot: false
  trans:
    corrupt: true
    batch_ot: true
    train_schedule: linear
    sample_schedule: linear
    sample_temp: 1.0
    vpsde_bmin: 0.1
    vpsde_bmax: 20.0
    potential: null
    potential_t_scaling: false
    rog:
      weight: 10.0
      cutoff: 5.0
    eps: 0.0001
  aatypes:
    corrupt: true
    schedule: linear
    schedule_exp_rate: 10
    temp: 0.1
    noise: 20.0
    do_purity: true
    train_extra_mask: 0.0
    interpolant_type: masking
    eps: 0.0001
  ss:
    corrupt: True
    train_schedule: 'linear'
    sample_schedule: 'linear'
    prior_mix_lambda: 1   # 0.0 = pure identity prior, 1.0 = pure random prior, intermediate values are mixed
  sampling:
    num_timesteps: ${inference.inference_step}
    do_sde: false
    self_condition: False
  self_condition: 1.0
  codesign_packing_prop: 0.5
  codesign_partial_prop: 0.0
  codesign_partial_ratio: -1
  conditional_multimer_prop: 0.5
  conditional_multimer_ratio: 0.5
  torsions:
    corrupt: true
  sidechain_start_t: 0.8
  refine_start_t: 0.8

preprocess:
  sigma_perturb: 0
  rotation_perturb: False
  link_config: BondFlow/config/link.csv
  allatom_backend: apm  

guidance:
  list:
    - name: type_soft_bond_count
      link_csv_path: ${preprocess.link_config}
      stage: post_step         # 或 post_step；both 更强一点
      bond_step: 0.1       # 不能是 null，不指定位置时需要软引导
      seq_step: 0.05       # 不能是 null，让序列也被引导成 CYS
      n_steps: 2
      sinkhorn_iters: 5
      schedule: linear
      debug: true

      region: "A|A"        # 只在设计链 A 内部找二硫键
      reference_space: design
      region_mode: include
      min_bond_distance: 3 # 避免太近的残基成键

      entropy_weight: 0.05
      entropy_mode: effective
      types:
        - name: disulfide
          mode: range_N
          min_N: 1
          max_N: 2
          loss_type: mse
          weight: 1.0
          top_k_soft: 0


    - name: type_soft_bond_count
      link_csv_path: ${preprocess.link_config}
      stage: post_step         # 或 post_step；both 更强一点
      bond_step: 0.1       
      seq_step: 0.0       
      n_steps: 2
      sinkhorn_iters: 5
      schedule: linear
      debug: true

      region: "A|A"        
      reference_space: design
      region_mode: include
      min_bond_distance: 3 # 避免太近的残基成键

      types:
        - name: isopeptide
          mode: exact_N
          target_N: 0
          loss_type: mse
          weight: 10.0

        - name: lactone
          mode: exact_N
          target_N: 0
          loss_type: mse
          weight: 10.0

    - name: clash
      link_csv_path: ${preprocess.link_config}
      start_t: 0.3
      weight: 0.05
      n_steps: 2
    
    - name: logits_bias
    # 'ALA','ARG','ASN','ASP','CYS','GLN','GLU','GLY','HIS','ILE',
    # 'LEU','LYS','MET','PHE','PRO','SER','THR','TRP','TYR','VAL',
    # A  R  N  D  C  Q  E  G  H  I
    # L  K  M  F  P  S  T  W  Y  V
      bias: [-0.25, -0.25, -0.0, -0, 0.0, -0.0, -0, -4.0, 0.0, 0.0,
            -0.0, -0.0, 0.0, 0.0, -0.5, -0.5, -0, 0.0, 0.0, 0.0]
      weight: 5
      schedule: linear
      power: 0.0
      auto_update_positions: false  # 关键：设置为 false   